select table_name from user_tables;

CREATE TABLE BIBLIOTECI 
(
 COD_BIB NUMBER(2) PRIMARY KEY,
 DENUMIRE VARCHAR2(20),
 LOCALITATE VARCHAR2(20),
 DIRECTOR VARCHAR2(20)
);

CREATE TABLE CARTI
(
 COD_CARTE NUMBER(3) PRIMARY KEY,
 TITLU VARCHAR2(15),
 AUTOR VARCHAR2(20),
 NR_PAG NUMBER(4),
 COD_BIBLIO NUMBER(2),
 CONSTRAINT FK_CARTI_BIBLIOTECI
 FOREIGN KEY(COD_BIBLIO)
 REFERENCES BIBLIOTECI(COD_BIB)
);

INSERT INTO BIBLIOTECI values(1, 'IOAN SLAVICI', 'TIMISOARA', 'POPESCU');
INSERT INTO BIBLIOTECI (COD_BIB, DENUMIRE, LOCALITATE)
 values(2, 'MIHAI EMINESCU', 'BACAU');

SELECT * 
FROM BIBLIOTECI;

SELECT DENUMIRE, LOCALITATE 
FROM BIBLIOTECI;

INSERT INTO CARTI values(1, 'MOARA CU NOROC', 'IOAN SLAVICI', 249, 1);
INSERT INTO CARTI values(2, 'LUCEAFARUL', 'MIHAI EMINESCU', 6, 2);

SELECT * 
FROM CARTI;

SELECT TITLU, LOCALITATE
FROM CARTI, BIBLIOTECI
WHERE 
 CARTI.COD_BIBLIO = BIBLIOTECI.COD_BIB;

DELETE FROM CARTI 
WHERE
 COD_BIBLIO = 2;

DELETE FROM BIBLIOTECI
WHERE
 COD_BIB = 2;

DROP TABLE CARTI;
DROP TABLE BIBLIOTECI;